// Literales

env:
  nulo: ${{ null }}
  booleano: ${{ false }}
  numeroEntero: ${{ 711 }}
  numeroFlotante: ${{ -9.2 }}
  numeroHexadecimal: ${{ 0xff }}
  numeroExponencial: ${{ -2.99e-2 }}
  string: Hola
  stringComillas: ${{ 'Hola' }}

// Operadores
// () Agrupación lógica
//  Índice
// .  Referencia de propiedad
// !  Not
// < Menor que
// <= Menor o igual que
// > Mayor
// >= Mayor o igual que
// == Igual
// != No Igual
&& Y
|| Or

// Principales funciones
if: ${{ <expresión> }}
contains(github.event.issue.labels.*.name, 'bug')
toJSON(value)
fromJSON(value)
