name: hola-mundo.ts gitHub actions
run-name: Â¡Estoy aprendiendo GitHub actions!

on:
  [push]
  
jobs:
  hola-mundo:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del Repositorio
      - uses: actions/checkout@v3

      # 3. Instalar ts-node
      - name: Install ts-node
        run: npm install -g ts-node typescript

      # 4. Ejecutar el script TypeScript
      - name: Execute TypeScript Script
        run: node --loader ts-node/esm index.ts
