name: hola-mundo.ts gitHub actions
run-name: Â¡Estoy aprendiendo GitHub actions!

on:
  [push]
  
jobs:
  hola-mundo:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          
      # 1. Checkout del Repositorio
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'

      # 3. Instalar ts-node
      - name: Install ts-node
        run: npm install

      # 4. Ejecutar el script TypeScript
      - name: Execute TypeScript Script (ESM mode)
        run: npx ts-node --transpileOnly index.ts
